

-- ««««««««««««««« SCRIPT BASE DE DATOS - anaserena pastry database   »»»»»»»»»»»»»»»

-- «««««««««««««««              SQL SERVER MANAGMENT                  »»»»»»»»»»»»»»»

-- ««««««««««««««« PROYECTO INTEGRADOR - ANASERENA SISTEMA DE GESTION »»»»»»»»»»»»»»»


CREATE DATABASE anaserena_pms_db;
USE anaserena_pms_db;
GO 

-- TABLA DOMICILIO
CREATE TABLE Domicilio (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NUMERO INT NOT NULL,
	BARRIO VARCHAR(MAX) NOT NULL,
	PISO VARCHAR(MAX) NULL,
	CIUDAD VARCHAR(MAX) NOT NULL,
	PROVINCIA VARCHAR(MAX) NOT NULL
);
GO

-- TABLA USUARIO
CREATE TABLE Usuario (
	ID INT PRIMARY KEY IDENTITY(1,1),
	USERNAME VARCHAR(MAX) NOT NULL,
	NOMBRECOMPLETO VARCHAR(MAX) NOT NULL,
	PASSWORD VARCHAR(MAX) NOT NULL,
	ROL VARCHAR(MAX) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1,
	INTENTOFALLIDOS INT NOT NULL DEFAULT 0,
	FECHAINGRESO DATETIME NOT NULL DEFAULT GETDATE(),
	IDDOMICILIO INT NULL,
	CONSTRAINT FK_Usuario_Domicilio FOREIGN KEY (IDDOMICILIO) REFERENCES Domicilio(ID)
);
GO

-- TABLA CLIENTE
CREATE TABLE Cliente (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(MAX) NOT NULL,
	APELLIDO VARCHAR(MAX) NOT NULL,
	TELEFONO VARCHAR(MAX) NULL,
	EMAIL VARCHAR(MAX) NULL,
	ACTIVO BIT NOT NULL DEFAULT 1,
	FECHAINGRESO DATETIME NOT NULL DEFAULT GETDATE(),
	IDDOMICILIO INT NULL,
	CONSTRAINT FK_Cliente_Domicilio FOREIGN KEY (IDDOMICILIO) REFERENCES Domicilio(ID)
);
GO

-- TABLA INGRDIENTES
CREATE TABLE INGREDIENTES (
	ID INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPCION VARCHAR(MAX) NULL,
	CODIGO VARCHAR(MAX) NOT NULL,
	NOMBRE VARCHAR(MAX) NOT NULL,
	STOCK DECIMAL(30) NOT NULL DEFAULT 0,
	UNIDADMEDIDA VARCHAR(MAX) NOT NULL,
	PRECIOUNITARIO DECIMAL(30) NOT NULL,
	ACTIVO BIT NOT NULL DEFAULT 1
);
GO

-- TABLA PRODUCTO
CREATE TABLE PRODUCTO (
	ID INT PRIMARY KEY IDENTITY(1,1),
	CODIGO VARCHAR(MAX) NOT NULL,
	NOMBRE VARCHAR(MAX) NOT NULL,
	DESCRIPCION VARCHAR(MAX) NULL,
	PRECIO DECIMAL(30) NOT NULL,
	CATEGORIA VARCHAR(MAX) NOT NULL,
	DISPONIBLE BIT NOT NULL DEFAULT 0,
	STOCK DECIMAL(30) NOT NULL DEFAULT 0,
	FECHACREACION DATETIME NOT NULL DEFAULT GETDATE()
);
GO

-- TABLA VENTA
CREATE TABLE Venta (
	ID INT PRIMARY KEY IDENTITY(1,1),
	FECHA DATETIME NOT NULL DEFAULT GETDATE(),
	TOTAL DECIMAL(30) NOT NULL DEFAULT 0,
	IDUSUARIO INT NOT NULL,
	IDCLIENTE INT NULL,
	CONSTRAINT FK_Venta_Usuario FOREIGN KEY (IDUSUARIO) REFERENCES Usuario(ID),
	CONSTRAINT FK_Venta_Cliente FOREIGN KEY (IDCLIENTE) REFERENCES Cliente(ID)
);
GO

-- TABLA DETALLE VENTA
CREATE TABLE DetalleVenta (
	ID INT PRIMARY KEY IDENTITY(1,1),
	CANTIDAD INT NOT NULL DEFAULT 0,
	PRECIOUNITARIO DECIMAL(30) NOT NULL,
	SUBTOTAL DECIMAL(30) NOT NULL,
	IDVENTA INT NOT NULL,
	IDPRODUCTO INT NOT NULL,
	CONSTRAINT FK_DetalleVenta_Venta FOREIGN KEY (IDVENTA) REFERENCES Venta(ID),
	CONSTRAINT FK_DetalleVenta_Producto FOREIGN KEY (IDPRODUCTO) REFERENCES Producto(ID)
);
GO


-- CONFIRMACION DE CORRECTA IMPLEMENTACION DE LA BBDD
PRINT 'Base de datos creada Exitosamente!';
